### ISSUE TITLE
Error: Search node_modules: No node_modules folder in this workspace.

### ISSUE THREAD

**Issue by chipit24** [jasonnutter/vscode-search-node-modules#3]
Just installed the extension and I get this error when trying to search:
> Error: Search node_modules: No node_modules folder in this workspace.

My `node_modules` folder is not in the root of my project, but at `src/node_modules`; could this be the issue?

**Comment by jasonnutter** [comment]
Yes, the issue is that your `node_modules` folder is not in the root of your project. I've been considering adding an option to specify this, sounds like it should be added.

**Comment by christophior** [comment]
Has this already been added?

**Comment by jasonnutter** [comment]
This has been added in 1.2.0, which is now available to install.

**Comment by borekb** [comment]
Our project which is a monorepo which contains many `node_modules` folders. Is there any chance this module would ever support it? Would be very useful.

**Comment by jasonnutter** [comment]
@borekb I'll take a look at adding that when I get chance to look into the new multi root workspaces.
