### ISSUE TITLE
Folder name configurable

### ISSUE THREAD

**Issue by boydy12** [jasonnutter/vscode-search-node-modules#4]
Awesome extension but would be even better if it were possible to set an array of folders configurable to search instead of only node_modules.

I guess the project would need a new name though..

**Comment by jasonnutter** [comment]
@boydy12 Right, I would like the plugin to be as simple as possible to configure and use, and supporting an array of folders would add complexity. I could add an option to specify the name of the `node_modules` folder, however.

**Comment by jasonnutter** [comment]
@boydy12 This has been added in 1.2.0, which is now available to install.

**Comment by SaranSank** [comment]
How can i search node_modules outof projects bcoz my project folder structure is like 
 
http://localhost/projects/mynodemodules/myproject

      mynodemodules->folder [ http://localhost/projects/mynodemodules/ ]
           -node_modules ->folder
      myproject->folder [ http://localhost/projects/mynodemodules/myproject ]
          -index.html
          -text.js
          -style.css
