### ISSUE TITLE
Is there any plan to support multi-root workspaces?

### ISSUE THREAD

**Issue by charles8xu** [jasonnutter/vscode-search-node-modules#6]

**Comment by jasonnutter** [comment]
Yup, planning to it soon.

**Comment by iatsiuk** [comment]
hi there, any updates on this?

**Comment by jasonnutter** [comment]
I've been busy, but I'll be looking at this soon. Sorry for the delay!

**Comment by jasonnutter** [comment]
Update on this, I've started a refactor to support multi-root workspaces, a little more involved than I thought, but hoping to have it done soon. Thanks again for being patient!

**Comment by jasonnutter** [comment]
New version has been published with support for multi-root workspaces, let me know if there are any issues!
