### ISSUE TITLE
Preview Markdown

### ISSUE THREAD

**Issue by tzeeh** [jasonnutter/vscode-search-node-modules#8]
Do you think it would be possible to add the functionality of opening any .md file in preview mode so we can see the formatted content. I know you can just open the file. Then go to your explorer sidebar and right click on the file and click preview, but it would save a lot of time to just be able to do it from the search box. Maybe have two options, one that says preview in case users want to select the regular .md file for some reason. Thanks love the extension.

**Comment by jasonnutter** [comment]
I prefer for the extension to stay simple and unopinionated, but I’ll consider it, thanks for the suggestion!
